services:
  proxy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - ${HTTPS_PORT}:443
      - ${HTTP_PORT}:80
    environment:
      - BASIC_AUTH_USERNAME
      - BASIC_AUTH_PASSWORD_HASH
      - BIND_ADDRESS
    volumes:
      - ./mounts/proxy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./volumes/proxy/config:/config:rw
      - ./volumes/proxy/data:/data:rw
      - ./volumes/proxy/srv:/srv:rw

  worker:
    build: ./services/worker
    depends_on:
      mqtt: { condition: service_healthy }
    environment:
      - MQTT_BROKER=mqtt
      - MQTT_PORT=1883
      - MQTT_TOPIC=solar
      - PUBLISH_INTERVAL=5

  node-red:
    image: nodered/node-red:3.1.15-debian
    depends_on:
      mqtt: { condition: service_healthy }
    volumes:
      - ./volumes/node-red:/data:rw

  mqtt:
    image: rabbitmq:3-alpine
    restart: unless-stopped
    hostname: mqtt
    command: '/bin/bash -c "rabbitmq-plugins enable --offline rabbitmq_mqtt; rabbitmq-server"'
    volumes:
      - ./volumes/mqtt/data:/var/lib/rabbitmq/
      - ./volumes/mqtt/log:/var/log/rabbitmq/
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
